### ISSUE TITLE
Steroids > 4.1.17 build fails for pure Cordova project

### ISSUE THREAD

**Issue by alexdrel** [AppGyver/steroids#1052]
```
Steroids Error
Debug Log:
Thu Oct 08 2015 20:06:47 GMT+0300 (IDT) requiring /[skipped]/node_modules/steroids/package.json
Thu Oct 08 2015 20:06:47 GMT+0300 (IDT) package.json#version: 4.1.20
Thu Oct 08 2015 20:06:47 GMT+0300 (IDT) Updater: Looking for update: https://updates.appgyver.com/v1/steroids/latest.json?os=Darwin&version=4.1.20&from=connect&user_id=332708&ionic=false&cordova=true
Thu Oct 08 2015 20:06:48 GMT+0300 (IDT) Starting push
Thu Oct 08 2015 20:06:48 GMT+0300 (IDT) Making with hooks.
Thu Oct 08 2015 20:06:48 GMT+0300 (IDT) Making dist/ for Cordova project...

Error with: steroids connect

TypeError: Cannot read property 'then' of undefined
    at /[skipped]/node_modules/steroids/src/steroids/project/Base.coffee:189:41
    at bound (domain.js:250:14)
    at runBound (domain.js:263:12)
    at tryCatcher (/[skipped]/node_modules/steroids/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/[skipped]/node_modules/steroids/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/[skipped]/node_modules/steroids/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromiseAtPostResolution (/[skipped]/node_modules/steroids/node_modules/bluebird/js/main/promise.js:244:10)
    at Async._drainQueue (/[skipped]/node_modules/steroids/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/[skipped]/node_modules/steroids/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/[skipped]/node_modules/steroids/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

It can be reproduced on the scaffolded SPA by adding config.xml in the project root.

**Comment by dantabel** [comment]
+1 
Tried to run steroids connect from the root of a new ionic project with exactly the same results as above

**Comment by amitparrikar** [comment]
Any solutions on the above issue ? @dantabel @alexdrel any luck?

**Comment by alexdrel** [comment]
@amitparrikar, given that the one line patch (listed above) was not merged in a year, it is safe to say it is not going to be fixed. As for me, I just switched to Cordova without Steroids.
