### ISSUE TITLE
"npm install steroids -g" fails with npm 3

### ISSUE THREAD

**Issue by harsaharsa** [AppGyver/steroids#1055]
**CURRENT WORKAROUND:** Use npm v2.x by running `npm install npm@2.x -g`

**DESCRIPTION OF PROBLEM**
Trying to run `npm install steroids -g` with npm v3.x results in the following error log:

```
  SOLINK_MODULE(target) Release/.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/harsa/.nvm/v0.12.7/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/Users/harsa/.nvm/v0.12.7/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/harsa/.nvm/v0.12.7/lib/node_modules/steroids/node_modules/fsevents
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
/Users/harsa/.nvm/v0.12.7/lib
└── (empty)

npm WARN EPEERINVALID generator-steroids@1.0.20 requires a peer of yo@>=1.0.0 but none was installed.
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/Users/harsa/.nvm/v0.12.7/bin/npm" "install" "steroids" "-g"
npm ERR! node v0.12.7
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE

npm ERR! fsevents@0.3.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fsevents@0.3.8 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the fsevents package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls fsevents
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/harsa/tmp/npm-debug.log
npm ERR! code 1
```

The `steroids` command is still available and e.g. `steroids create` works fine. However, the `grunt-steroids` peer dependencies don't install correctly with npm v3.x, leading to `steroids connect` failing.

**Comment by mansoor-spark** [comment]
Hi Harsa -
I downgraded my npm version 3 to npm version 2 but I still get the below error when installing Steroids:
 
Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✖ npm version

Your npm version is outdated.

Upgrade to the latest version by running:
npm install -g npm


Found potential issues on your machine :(
/usr/local/bin/steroids -> /usr/local/lib/node_modules/steroids/bin/steroids
