### ISSUE TITLE
java.lang.NoSuchMethodError: android.webkit.WebView.evaluateJavascript

### ISSUE THREAD

**Issue by ezramorse** [AppGyver/steroids#1073]
We shipped into production and getting killed on this one. Version 4.1, native webview:

```
java.lang.NoSuchMethodError: android.webkit.WebView.evaluateJavascript
	at com.appgyver.webview.AGWebView.evaluateJavascript(AGWebView.java:188)
	at com.appgyver.webview.AGWebViewBase$2.run(AGWebViewBase.java:341)
	at android.app.Activity.runOnUiThread(Activity.java:4673)
	at com.appgyver.webview.AGWebViewBase.executeJavascriptAsync(AGWebViewBase.java:335)
	at com.appgyver.webview.AGWebViewBase.canRemoveFromStack(AGWebViewBase.java:364)
	at com.appgyver.ui.LayersScreenView.popAllContainers(LayersScreenView.java:535)
	at com.appgyver.ui.ViewStack.notifyLayerRemoved(ViewStack.java:1283)
	at com.appgyver.ui.ViewStack.notifyScreenRemoved(ViewStack.java:1310)
	at com.appgyver.ui.ViewStack$16.run(ViewStack.java:1432)
	at com.appgyver.utils.Async.invoke(Async.java:98)
	at com.appgyver.utils.Async.notifyResolved(Async.java:90)
	at com.appgyver.utils.Async.checkIfIsResolve(Async.java:162)
	at com.appgyver.utils.Async.access$400(Async.java:16)
	at com.appgyver.utils.Async$1.invoke(Async.java:56)
	at $Proxy0.run(Native Method)
	at com.appgyver.ui.animation.AnimationContext$1.onAnimationEnd(AnimationContext.java:121)
	at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:982)
	at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1020)
	at android.animation.ValueAnimator.access$400(ValueAnimator.java:50)
	at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:630)
	at android.animation.ValueAnimator$AnimationHandler.run(ValueAnimator.java:646)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
	at android.view.Choreographer.doCallbacks(Choreographer.java:562)
	at android.view.Choreographer.doFrame(Choreographer.java:531)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
	at android.os.Handler.handleCallback(Handler.java:730)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5136)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by ezramorse** [comment]
All happening on android version  < 4.4 of course

**Comment by pre** [comment]
Hi, we're terrible sorry about this. It has been fixed in Android 4.2.0 which was just released. 

Could you please confirm that it fixes the issue for you? Thanks :)

**Comment by ezramorse** [comment]
Thank you so much for the quick response! We couldn't be happier this morning. We are going to put a copy into testing in a moment and will let you know the results.


In our haste last night, we threw up a relatively untested XWALK build as a hail mary. The results were somewhat worse. 15 crash reports in the last 4 hours. 10 of these:
```
junit.framework.AssertionFailedError: Please have your activity extend XWalkActivity for shared mode
	at junit.framework.Assert.fail(Assert.java:50)
	at org.xwalk.core.XWalkCoreWrapper.initEmbeddedMode(XWalkCoreWrapper.java:180)
	at org.xwalk.core.XWalkPreferences.setValue(XWalkPreferences.java:105)
	at com.appgyver.webview.XWalkRuntimeConfig.<init>(XWalkRuntimeConfig.java:22)
	at com.appgyver.runtime.standalone.chromium.StandaloneChromiumApplication.onCreate(StandaloneChromiumApplication.java:12)```

Android 5/5.1.

We have a very large user base so these come in relatively quickly. Let me know if there is a good contact channel for sharing crash reports and we will forward all data if you want

**Comment by pre** [comment]
That `Please have your activity extend XWalkActivity for shared mode` error was about missing 64 bit support (the actual error message is couple of lines before the stack trace, it 's not visible on your paste).

Version 4.2.0 provides support for 64bit devices and this crash will not happen either.

**Comment by ezramorse** [comment]
Thanks so much. So I think we're set with 4.2. The only other crash lingering out there on webview that I see is:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sevencupsoftea.app/com.appgyver.runtime.standalone.chromium.MainActivity}: java.lang.RuntimeException: Invalid property name: İd
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
	at android.app.ActivityThread.-wrap11(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.RuntimeException: Invalid property name: İd
	at com.appgyver.app.ApplicationConfigParser.setPropertyValue(ApplicationConfigParser.java:337)
	at com.appgyver.app.ApplicationConfigParser.copyBigInt(ApplicationConfigParser.java:305)
	at com.appgyver.app.ApplicationConfigParser.setAccessibleFields(ApplicationConfigParser.java:146)
	at com.appgyver.app.ApplicationConfigParser.loadApplicationJson(ApplicationConfigParser.java:136)
	at com.appgyver.app.ApplicationConfigParser.loadApplicationJsonFromSteroidsBaseDir(ApplicationConfigParser.java:131)
	at com.appgyver.app.ApplicationDescription.loadApplicationJsonFromAssets(ApplicationDescription.java:390)
	at com.appgyver.android.application.AGAndroidApplication.loadSteroidsApplication(AGAndroidApplication.java:74)
	at com.appgyver.standalone.StandaloneApplication.loadSteroidsApplication(StandaloneApplication.java:17)
	at com.appgyver.android.application.ApplicationActivity.loadSteroidsApplication(ApplicationActivity.java:187)
	at com.appgyver.android.application.ApplicationActivity.onCreate(ApplicationActivity.java:72)
	at com.appgyver.standalone.StandaloneApplicationActivity.onCreate(StandaloneApplicationActivity.java:14)
	at com.appgyver.runtime.standalone.chromium.MainActivity.onCreate(MainActivity.java:13)
	at android.app.Activity.performCreate(Activity.java:6237)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
	... 9 more
```

3 instances. Android 4.1, 4.4, 6.0. Ideas? Any way to fix this on my end?

**Comment by ezramorse** [comment]
Just to follow up, this update definitely worked. Great job Appgyver.

**Comment by pre** [comment]
Thanks for the info, i'm closing this issue.

About the other one: `Invalid property name: İd` .. I cannot find a string `İd` in our codebase. Could you try `git grep -i İd` on yours? I suspect you have that in your application.coffee, structure.coffee or such, which tries to define that property (you see the funny looking `İ` character there). 

Runtime shouldn't crash for invalid property names anyhow, so i'll write that one down as a bug in the parser.
