### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by ezramorse** [AppGyver/steroids#1080]
```
java.lang.NullPointerException
    at com.appgyver.app.AGWebViewClientBase.executeInitialJsString(AGWebViewClientBase.java:497)
    at com.appgyver.app.AGWebViewClientBase.onPageFinished(AGWebViewClientBase.java:471)
    at com.appgyver.app.AGWebViewClientBase.onPageFinished(AGWebViewClientBase.java:419)
    at com.appgyver.webview.AGWebViewClient$1.onPageFinished(AGWebViewClient.java:53)
    at com.android.webview.chromium.WebViewContentsClientAdapter.onPageFinished(WebViewContentsClientAdapter.java:449)
    at com.android.org.chromium.android_webview.AwContentsClient$AwWebContentsObserver$1.run(AwContentsClient.java:73)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:146)
    at android.app.ActivityThread.main(ActivityThread.java:5602)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
    at dalvik.system.NativeStart.main(Native Method)
```

Android 4.4

Device: Galaxy Note2 (t0lteatt)

Ideas?

Build 4.2.1

**Comment by pre** [comment]
I have an idea what is the object being null, but it's not clear to me why it's null at that point. I included this on the backlog to check it it out.
