### ISSUE TITLE
What is DexIndexOverflowException and how to avoid it?

### ISSUE THREAD

**Issue by blanedaze** [AppGyver/steroids#1084]
Hi, I was finding a way to open the image in a image viewer-like app or plugin, and I tried to build the crosswalk scanner 4.2.1 with the plugin `https://github.com/wymsee/cordova-imagePicker.git`, and the Appgyver builder return me this error log:

```io
BUILD PROPERTIES
================
minSdkVersion: 14
targetSdkVersion: 21
versionCode: 1
versionName: 1.0.0
keystoreFilename: ../../../../STAGING/keys/keystore
keyAlias: datum
storePassword: (hidden)
keyPassword: (hidden)

:runtimes:ScannerChromium:indexAssets
:runtimes:ScannerChromium:compileArm_and_x86DebugAidl
:runtimes:ScannerChromium:compileArm_and_x86DebugRenderscript
:runtimes:ScannerChromium:generateArm_and_x86DebugBuildConfig
:runtimes:ScannerChromium:generateArm_and_x86DebugResValues
:runtimes:ScannerChromium:generateArm_and_x86DebugResources
:runtimes:ScannerChromium:mergeArm_and_x86DebugResources/Users/administrator/app-builder/STAGING/client/runtimes/ScannerChromium/build/intermediates/exploded-aar/client.modules/AGScanner/unspecified/res/drawable/btn_reload_pressed.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/administrator/app-builder/STAGING/client/runtimes/ScannerChromium/build/intermediates/exploded-aar/client.modules/AGScanner/unspecified/res/drawable/logo_appgyver_scanner.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/administrator/app-builder/STAGING/client/runtimes/ScannerChromium/build/intermediates/exploded-aar/client.modules/AGScanner/unspecified/res/drawable/btn_redownload_normal.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/administrator/app-builder/STAGING/client/runtimes/ScannerChromium/src/main/res/drawable-mdpi/app_icon.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/administrator/app-builder/STAGING/client/runtimes/ScannerChromium/build/intermediates/exploded-aar/client.modules/AGScanner/unspecified/res/drawable-mdpi-v4/logo_es.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/administrator/app-builder/STAGING/client/runtimes/ScannerChromium/build/intermediates/exploded-aar/client.modules/AGScanner/unspecified/res/drawable-xhdpi-v4/logo_es.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/administrator/app-builder/STAGING/client/runtimes/ScannerChromium/build/intermediates/exploded-aar/client.modules/AGScanner/unspecified/res/drawable-nodpi-v4/scanner_background.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/administrator/app-builder/STAGING/client/runtimes/ScannerChromium/build/intermediates/exploded-aar/client.modules/AGScanner/unspecified/res/drawable/btn_steroids_scan_normal.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/administrator/app-builder/STAGING/client/runtimes/ScannerChromium/src/main/res/drawable-hdpi/app_icon.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/administrator/app-builder/STAGING/client/runtimes/ScannerChromium/build/intermediates/exploded-aar/client.modules/AGScanner/unspecified/res/drawable/btn_steroids_scan_pressed.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/administrator/app-builder/STAGING/client/runtimes/ScannerChromium/build/intermediates/exploded-aar/client.modules/AGScanner/unspecified/res/drawable/btn_reload_normal.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/administrator/app-builder/STAGING/client/runtimes/ScannerChromium/build/intermediates/exploded-aar/client.modules/AGScanner/unspecified/res/drawable-xxhdpi-v4/logo_es.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/administrator/app-builder/STAGING/client/runtimes/ScannerChromium/build/intermediates/exploded-aar/client.modules/AGCordova/unspecified/res/drawable/icon.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/administrator/app-builder/STAGING/client/runtimes/ScannerChromium/build/intermediates/exploded-aar/client.modules/AGScanner/unspecified/res/drawable-hdpi-v4/logo_es.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/administrator/app-builder/STAGING/client/runtimes/ScannerChromium/build/intermediates/exploded-aar/client.modules/AGScanner/unspecified/res/drawable/freshlogo.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/administrator/app-builder/STAGING/client/runtimes/ScannerChromium/build/intermediates/exploded-aar/client.modules/AGScanner/unspecified/res/drawable/btn_redownload_pressed.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/administrator/app-builder/STAGING/client/runtimes/ScannerChromium/src/main/res/drawable-xhdpi/app_icon.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited

:runtimes:ScannerChromium:processArm_and_x86DebugManifest
:runtimes:ScannerChromium:processArm_and_x86DebugResourceswarning: string 'menu_settings' has no default translation.

:runtimes:ScannerChromium:generateArm_and_x86DebugSources
:runtimes:ScannerChromium:compileArm_and_x86DebugJava
:runtimes:ScannerChromium:preDexArm_and_x86Debug
:runtimes:ScannerChromium:dexArm_and_x86Debug
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexIndexOverflowException: field ID not in [0, 0xffff]: 65536
	at com.android.dx.merge.DexMerger$5.updateIndex(DexMerger.java:479)
	at com.android.dx.merge.DexMerger$IdMerger.mergeSorted(DexMerger.java:283)
	at com.android.dx.merge.DexMerger.mergeFieldIds(DexMerger.java:468)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:167)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runtimes:ScannerChromium:dexArm_and_x86Debug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  	/usr/local/opt/android-sdk/build-tools/23.0.1/dx --dex --output /Users/administrator/app-builder/STAGING/client/runtimes/ScannerChromium/build/intermediates/dex/arm_and_x86/debug --input-list=/Users/administrator/app-builder/STAGING/client/runtimes/ScannerChromium/build/intermediates/tmp/dex/arm_and_x86/debug/inputList.txt
  Error Code:
  	2
  Output:
  	
  	UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexIndexOverflowException: field ID not in [0, 0xffff]: 65536
  		at com.android.dx.merge.DexMerger$5.updateIndex(DexMerger.java:479)
  		at com.android.dx.merge.DexMerger$IdMerger.mergeSorted(DexMerger.java:283)
  		at com.android.dx.merge.DexMerger.mergeFieldIds(DexMerger.java:468)
  		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:167)
  		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
  		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
  		at com.android.dx.command.dexer.Main.run(Main.java:277)
  		at com.android.dx.command.dexer.Main.main(Main.java:245)
  		at com.android.dx.command.Main.main(Main.java:106)
  	


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4 mins 16.677 secs
```
What does this error imply and how do I avoid it?

**Comment by harsaharsa** [comment]
See https://github.com/AppGyver/steroids/issues/1086 – closing as duplicate
