### ISSUE TITLE
InitialView on Android is stuck at loading when Tab1 is arbitrarily small in size

### ISSUE THREAD

**Issue by ezramorse** [AppGyver/steroids#1085]
We are using Webview and steroids 4.2.1

Upon initial view, the following code is executed successfully:

```
supersonic.ui.initialView.dismiss();
```

All our tabs are loaded properly in "chrome://inspect" but the initial view remiains. The only issue is that they are listed as:

```
https://app.xxxx.com/tab1.php
https://app.xxxx.com/tab1.php
empty
inspect
```

There is an "empty" instead of a "at (0, 38) size 480 × 690"

Further calls to dismiss the initial view result in an exception:

```
supersonic.logger.error: supersonic.ui.initialView.dismiss rejected: The specified child already has a parent. You must call removeView() on the child's parent first.(anonymous function) @ supersonic.core.min.js:10(anonymous function) @ supersonic.core.min.js:4(anonymous function) @ supersonic.core.min.js:5i @ supersonic.core.min.js:5a.push @ supersonic.core.min.js:4a.handleEvent @ supersonic.core.min.js:4(anonymous function) @ supersonic.core.min.js:4b.push @ supersonic.core.min.js:4in @ supersonic.core.min.js:10(anonymous function) @ supersonic.core.min.js:11e @ supersonic.core.min.js:7b._settlePromiseFromHandler @ supersonic.core.min.js:6b._settlePromiseAt @ supersonic.core.min.js:6b._settlePromises @ supersonic.core.min.js:6e._drainQueue @ supersonic.core.min.js:5e._drainQueues @ supersonic.core.min.js:5drainQueues @ supersonic.core.min.js:5
supersonic.core.min.js:5 Unhandled rejection Error: [object Object]
    at Object.ensureErrorObject (http://localhost/components/supersonic/supersonic.core.min.js:7:9223)
    at b._rejectCallback (http://localhost/components/supersonic/supersonic.core.min.js:6:11736)
    at Function.b.reject.b.rejected (http://localhost/components/supersonic/supersonic.core.min.js:6:7847)
    at http://localhost/components/supersonic/supersonic.core.min.js:11:17557
    at e (http://localhost/components/supersonic/supersonic.core.min.js:7:6770)
    at b._settlePromiseFromHandler (http://localhost/components/supersonic/supersonic.core.min.js:6:12282)
    at b._settlePromiseAt (http://localhost/components/supersonic/supersonic.core.min.js:6:13551)
    at b._settlePromises (http://localhost/components/supersonic/supersonic.core.min.js:6:15416)
    at e._drainQueue (http://localhost/components/supersonic/supersonic.core.min.js:5:10438)
    at e._drainQueues (http://localhost/components/supersonic/supersonic.core.min.js:5:10499)
    at MutationObserver.drainQueues (http://localhost/components/supersonic/supersonic.core.min.js:5:9208)
```

I can replicate this 90% of the time by using the following HTML in tab1:

```
<!DOCTYPE html>
<html>
<head>
</head>
<body>
<h1>Test Page</h1>
</body>
</html>
```

Including a link to cordova, steroids, or other assets can reduce the chance of this happening.

For us this is a huge problem. Our tabs point to remote https assets. If our AWS load balancer serves the incorrect response on tab1, then someone's entire app will be frozen on the initial view (which is blank) and theyll have to reload app to access it. We've spent 2 weeks fighting a barrage of complaints about people frozen on white screens. This is the primary reproducible cause.

As far as I can tell via testing, the other tabs and drawer views can be of any size. The key here is tab 1 (which we don't even want to load first anyway).

**Comment by ezramorse** [comment]
This even happens with local assets. We've retooled our app to first load all local pages, and then perform redirects. On a Nexus 6 (using webviews since crosswalk crashes for ios 5.1 above), the white screen issue comes about 1 out of 3 times of loading.

With chrome inspect, the result is the same. The initialView is still there, all the other tabs are loaded, and their positions are "empty" (besides the initial view).

**Comment by ezramorse** [comment]
Could this be related:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference
	at com.appgyver.ui.LayersScreenView.performSequentialAnimationIn(LayersScreenView.java:229)
	at com.appgyver.ui.LayersScreenView.animateLayerIn(LayersScreenView.java:211)
	at com.appgyver.ui.LayersScreenView.presentContainer(LayersScreenView.java:159)
	at com.appgyver.ui.ViewStack$8.loadTabContents(ViewStack.java:680)
	at com.appgyver.ui.TabScreenView$2.run(TabScreenView.java:173)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5624)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
```

All on Android 5.0 and above with Platform webview

**Comment by ezramorse** [comment]
As of now, by getting rid of the initialview completely, it has "fixed" this.

I have noticed that if "dismissInitialView" is sent to the native bridge prior to the window receiving the AG_WEBVIEW_UUID, the udid field in the animation is undefined (even if you wait for "deviceready"). We are now testing to see if this is the culprit. 

Im also curious what happens if no fade animation is sent at all in the native call

**Comment by pre** [comment]
Thank you very much for the investigation. I'll take a look on this very soon.
