### ISSUE TITLE
Too many plugins cause DexIndexOverflowException in Crosswalk Android builds

### ISSUE THREAD

**Issue by bilalsoomro** [AppGyver/steroids#1086]
Here is a snippet of the build log...

UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexIndexOverflowException: Cannot merge new index 66757 into a non-jumbo instruction!
    at com.android.dx.merge.InstructionTransformer.jumboCheck(InstructionTransformer.java:109)
    at com.android.dx.merge.InstructionTransformer.access$800(InstructionTransformer.java:26)
    at com.android.dx.merge.InstructionTransformer$StringVisitor.visit(InstructionTransformer.java:72)
    at com.android.dx.io.CodeReader.callVisit(CodeReader.java:114)
    at com.android.dx.io.CodeReader.visitAll(CodeReader.java:89)
    at com.android.dx.merge.InstructionTransformer.transform(InstructionTransformer.java:49)
    at com.android.dx.merge.DexMerger.transformCode(DexMerger.java:842)
    at com.android.dx.merge.DexMerger.transformMethods(DexMerger.java:813)
    at com.android.dx.merge.DexMerger.transformClassData(DexMerger.java:786)
    at com.android.dx.merge.DexMerger.transformClassDef(DexMerger.java:682)
    at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:542)
    at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
    at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
    at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
    at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
    at com.android.dx.command.dexer.Main.run(Main.java:277)
    at com.android.dx.command.dexer.Main.main(Main.java:245)
    at com.android.dx.command.Main.main(Main.java:106)

 FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':runtimes:ScannerChromium:dexArm_and_x86Debug'.
  
  > com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  > /usr/local/opt/android-sdk/build-tools/23.0.1/dx --dex --output /Users/administrator/app-builder/STAGING/client/runtimes/ScannerChromium/build/intermediates/dex/arm_and_x86/debug --input-list=/Users/administrator/app-builder/STAGING/client/runtimes/ScannerChromium/build/intermediates/tmp/dex/arm_and_x86/debug/inputList.txt
  > Error Code:
  >   2
  > Output:
  
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexIndexOverflowException: Cannot merge new index 66757 into a non-jumbo instruction!
        at com.android.dx.merge.InstructionTransformer.jumboCheck(InstructionTransformer.java:109)
        at com.android.dx.merge.InstructionTransformer.access$800(InstructionTransformer.java:26)
        at com.android.dx.merge.InstructionTransformer$StringVisitor.visit(InstructionTransformer.java:72)
        at com.android.dx.io.CodeReader.callVisit(CodeReader.java:114)
        at com.android.dx.io.CodeReader.visitAll(CodeReader.java:89)
        at com.android.dx.merge.InstructionTransformer.transform(InstructionTransformer.java:49)
        at com.android.dx.merge.DexMerger.transformCode(DexMerger.java:842)
        at com.android.dx.merge.DexMerger.transformMethods(DexMerger.java:813)
        at com.android.dx.merge.DexMerger.transformClassData(DexMerger.java:786)
        at com.android.dx.merge.DexMerger.transformClassDef(DexMerger.java:682)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:542)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)

**Comment by harsaharsa** [comment]
This is happening if there are too many methods included in an Android build. Crosswalk unfortunately adds a LOT of methods, so the end result is that if you have too many plugins included, the build won't compile. We're looking into ways to overcome this, but for now, the only immediate remedy is to trim down the amount of plugin used (or the number of methods declared in those plugins). I updated the issue title to match.

**Comment by davistan** [comment]
There's a work around that perhaps can be used - refer to comment with jarjar utility https://groups.google.com/forum/#!topic/android-developers/eyc2z-madSQ. We can repackage the huge jar library that comes with the plugin to smaller jar to avoid hitting the dex limit.
