### ISSUE TITLE
High CPU usage in Android

### ISSUE THREAD

**Issue by bilalsoomro** [AppGyver/steroids#1091]
I've noticed that our appgyver android app is using high CPU in Android recently. In background its around 6% when all the other apps are below 1% and on foreground the app is using 16-20% and sometimes jumps up to 30%. Is this normal? Thanks

Edit:
The build is the platform WebView build using version is 4.2.1 and we are testing on a Android 5.0.2 Lollipop device. And the issue is similar to this https://github.com/AppGyver/steroids/issues/583

**Comment by harsaharsa** [comment]
Thanks for reporting! We'll look into this. So this is a standalone app, not a Scanner build? Have you tested if the same behavior occurs on a Crosswalk build?

**Comment by sunny061** [comment]
@harsaharsa I have noticed high CPU usage in both standalone webview builds and scanner webview builds. I have not tested the Crosswalk standalone or scanner build as we are not using it. I will test it out if I get some time.

**Comment by sunny061** [comment]
I tried building a crosswalk version and the build keeps failing. Here is the build error log.

:runtimes:StandaloneChromium:indexAssets
:runtimes:StandaloneChromium:compileArm_and_x86DebugAidl
:runtimes:StandaloneChromium:compileArm_and_x86DebugRenderscript
:runtimes:StandaloneChromium:generateArm_and_x86DebugBuildConfig
:runtimes:StandaloneChromium:generateArm_and_x86DebugResValues
:runtimes:StandaloneChromium:generateArm_and_x86DebugResources
:runtimes:StandaloneChromium:mergeArm_and_x86DebugResources/Users/administrator/app-builder/STAGING/client/runtimes/StandaloneChromium/src/main/res/drawable-mdpi/app_icon.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/administrator/app-builder/STAGING/client/runtimes/StandaloneChromium/src/main/res/drawable-hdpi/app_icon.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/administrator/app-builder/STAGING/client/runtimes/StandaloneChromium/src/main/res/drawable-xhdpi/app_icon.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited

:runtimes:StandaloneChromium:processArm_and_x86DebugManifest
:runtimes:StandaloneChromium:processArm_and_x86DebugResourceswarning: string 'menu_settings' has no default translation.

:runtimes:StandaloneChromium:generateArm_and_x86DebugSources
:runtimes:StandaloneChromium:compileArm_and_x86DebugJava
:runtimes:StandaloneChromium:preDexArm_and_x86Debug
:runtimes:StandaloneChromium:dexArm_and_x86Debug
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexIndexOverflowException: Cannot merge new index 65593 into a non-jumbo instruction!
	at com.android.dx.merge.InstructionTransformer.jumboCheck(InstructionTransformer.java:109)
	at com.android.dx.merge.InstructionTransformer.access$800(InstructionTransformer.java:26)
	at com.android.dx.merge.InstructionTransformer$StringVisitor.visit(InstructionTransformer.java:72)
	at com.android.dx.io.CodeReader.callVisit(CodeReader.java:114)
	at com.android.dx.io.CodeReader.visitAll(CodeReader.java:89)
	at com.android.dx.merge.InstructionTransformer.transform(InstructionTransformer.java:49)
	at com.android.dx.merge.DexMerger.transformCode(DexMerger.java:842)
	at com.android.dx.merge.DexMerger.transformMethods(DexMerger.java:813)
	at com.android.dx.merge.DexMerger.transformClassData(DexMerger.java:786)
	at com.android.dx.merge.DexMerger.transformClassDef(DexMerger.java:682)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:542)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runtimes:StandaloneChromium:dexArm_and_x86Debug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  	/usr/local/opt/android-sdk/build-tools/23.0.1/dx --dex --output /Users/administrator/app-builder/STAGING/client/runtimes/StandaloneChromium/build/intermediates/dex/arm_and_x86/debug --input-list=/Users/administrator/app-builder/STAGING/client/runtimes/StandaloneChromium/build/intermediates/tmp/dex/arm_and_x86/debug/inputList.txt
  Error Code:
  	2
  Output:
  	
  	UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexIndexOverflowException: Cannot merge new index 65593 into a non-jumbo instruction!
  		at com.android.dx.merge.InstructionTransformer.jumboCheck(InstructionTransformer.java:109)
  		at com.android.dx.merge.InstructionTransformer.access$800(InstructionTransformer.java:26)
  		at com.android.dx.merge.InstructionTransformer$StringVisitor.visit(InstructionTransformer.java:72)
  		at com.android.dx.io.CodeReader.callVisit(CodeReader.java:114)
  		at com.android.dx.io.CodeReader.visitAll(CodeReader.java:89)
  		at com.android.dx.merge.InstructionTransformer.transform(InstructionTransformer.java:49)
  		at com.android.dx.merge.DexMerger.transformCode(DexMerger.java:842)
  		at com.android.dx.merge.DexMerger.transformMethods(DexMerger.java:813)
  		at com.android.dx.merge.DexMerger.transformClassData(DexMerger.java:786)
  		at com.android.dx.merge.DexMerger.transformClassDef(DexMerger.java:682)
  		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:542)
  		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
  		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
  		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
  		at com.android.dx.command.dexer.Main.run(Main.java:277)
  		at com.android.dx.command.dexer.Main.main(Main.java:245)
  		at com.android.dx.command.Main.main(Main.java:106)
  	


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by harsaharsa** [comment]
Thanks for the report! We'll see what could be done about this.
