### ISSUE TITLE
Android (Fresh) Scanner App Crash

### ISSUE THREAD

**Issue by neophob** [AppGyver/steroids#845]
The last Android Edge Builds (4.0.5+) crash when I try to use the Scanner 

The last version I use that work is Android 4.0.4-edge3. I didn't test all releases between but they crash the camera. I use Android 4.4.4, CM11, OneM8

**Comment by pre** [comment]
It's probably this Crosswalk issue: https://github.com/AppGyver/steroids/issues/698

Do you experience the same problem using the  Platform WebView?

**Comment by neophob** [comment]
No this is not related to #698 as the crash is instant when the camera should start (when I press the SCAN button). I'll verify with the latest Platform Webview build

**Comment by neophob** [comment]
Here is the `adb logcat` output:

```
I/ActivityManager(  693): START u0 {cmp=com.company.scanner/com.appgyver.scanner.ImageScannerActivity} from pid 10411
I/ActivityManager(  693): Killing 9528:com.google.android.apps.plus/u0a31 (adj 15): empty #17
E/AndroidRuntime(10411): FATAL EXCEPTION: main
E/AndroidRuntime(10411): Process: com.company.scanner, PID: 10411
E/AndroidRuntime(10411): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.company.scanner/com.appgyver.scanner.ImageScannerActivity}: java.lang.RuntimeException: CAMERA OPEN FAILED
E/AndroidRuntime(10411): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2212)
E/AndroidRuntime(10411): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2271)
E/AndroidRuntime(10411): 	at android.app.ActivityThread.access$800(ActivityThread.java:144)
E/AndroidRuntime(10411): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205)
E/AndroidRuntime(10411): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(10411): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(10411): 	at android.app.ActivityThread.main(ActivityThread.java:5146)
E/AndroidRuntime(10411): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(10411): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(10411): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
E/AndroidRuntime(10411): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
E/AndroidRuntime(10411): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(10411): Caused by: java.lang.RuntimeException: CAMERA OPEN FAILED
E/AndroidRuntime(10411): 	at com.appgyver.scanner.ImageScannerActivity.getCameraInstance(ImageScannerActivity.java:92)
E/AndroidRuntime(10411): 	at com.appgyver.scanner.ImageScannerActivity.onCreate(ImageScannerActivity.java:65)
E/AndroidRuntime(10411): 	at android.app.Activity.performCreate(Activity.java:5231)
E/AndroidRuntime(10411): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
E/AndroidRuntime(10411): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2169)
E/AndroidRuntime(10411): 	... 11 more
W/ActivityManager(  693):   Force finishing activity com.company.scanner/com.appgyver.scanner.ImageScannerActivity
W/ActivityManager(  693):   Force finishing activity com.company.scanner/com.appgyver.runtime.scanner.MainActivity 
```

**Comment by neophob** [comment]
OK then, I fixed this issue by manually adding the camera permission to the build settings. I guess pre 4.0.5 build had this permissions added for the scanner build.

-> I assume the scanner build has the needed permissions added by default, but I was wrong. I this documented?

**Comment by harsaharsa** [comment]
Thanks for cracking it down – we'll investigate. Sounds like a bug – you shouldn't be able to unset Camera permission for Scanner builds, since it's absolutely required, but it's possible that we overlooked this.

**Comment by neophob** [comment]
Yep, I verified the Android 4.0.4-edge3 build (which has the camera permission set) while 4.0.5 builds do not have those permission set (per default)

**Comment by AndrasMilassin** [comment]
Same here. On 4.0.5-edge12, I unchecked the Camera permission - as it's not required by my app - and the Scanner app fails to load the camera part.
