### ISSUE TITLE
Apps try to load cloud-resources.js even if Data has not been set up

### ISSUE THREAD

**Issue by harsaharsa** [AppGyver/steroids#896]
The `cloud-resources.js` file is used by Supersonic Data to define the available models based on your cloud configuration. Currently, the `grunt-steroids` task [steroids-inject-cloud-resources-js](https://github.com/AppGyver/grunt-steroids/blob/master/tasks/fresh/steroids-setup-cloud-resources.coffee) always injects the `<script>` tag, even though the file itself is only created if the app has data initialized.

This leads to a mystical "Resource not found" error on regular apps. `grunt-steroids` should only inject the `<script>` tag if data is set up.

**Comment by zulfatilyasov** [comment]
+1
I am facing the same issue

**Comment by GayanJayasundara** [comment]
same issue for me.

**Comment by zeitrapha** [comment]
same issue here.
angular is trying to load the cloud-resources.js. for me, this is useless because, i did not configure any cloud resources. looking at the output in chrome dev tools, it looks like cloud-resources.js is there, but with following content (?!?!) :
```
<html>
<head>
    <meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' />
 </head>
 <body>
    <h1>404 Not Found</h1>
    /cloud-resources.js was not found.
</body>
</html>
```
anyway... every single page starts trying to load and read cloud-resources.js and results in this errer:
```
Uncaught SyntaxError: Unexpected token < localhost/cloud-resources.js:1
Unhandled rejection TypeError: Cannot read property 'querySelectorAll' of null
    at http://localhost/components/supersonic/supersonic.js:29597:54
    at http://localhost/components/supersonic/supersonic.js:29598:7
    at tryCatcher (http://localhost/components/supersonic/supersonic.js:18041:31)
    at Promise.module.exports.Promise._settlePromiseFromHandler (http://localhost/components/supersonic/supersonic.js:16193:31)
    at Promise.module.exports.Promise._settlePromiseAt (http://localhost/components/supersonic/supersonic.js:16269:18)
    at Promise.module.exports.Promise._settlePromises (http://localhost/components/supersonic/supersonic.js:16385:14)
    at Async._drainQueue (http://localhost/components/supersonic/supersonic.js:13762:16)
    at Async._drainQueues (http://localhost/components/supersonic/supersonic.js:13772:10)
    at MutationObserver.drainQueues (http://localhost/components/supersonic/supersonic.js:13697:14) localhost/components/supersonic/supersonic.js:14539
```
any suggestions or is there a workaround to manuel get rid of generating following lines into the projects output:
```
<!-- Cloud resource definition file for Supersonic Data -->
  <script src="/cloud-resources.js"></script>
```
thanks for any help!!! (or if i missunderstood, what is going on here???)

**Comment by jublo** [comment]
![image](https://cloud.githubusercontent.com/assets/6348321/9626595/00383f96-515f-11e5-8aa9-ef3722fbb439.png)

**Comment by GayanJayasundara** [comment]
@jublo @zeitrapha  Workaround : Just create mock cloud file.

**Comment by jublo** [comment]
@GayanJayasundara How would I create that file? It's not within the `dist` folder, is it?

**Comment by GayanJayasundara** [comment]
@jublo I had this issue on my app few months back. As I remember what I did was create a cloud file (I didn't use those files within my application) It is not in your app/ dist. you should create cloud data model. angular trying to load Cloud-resource.js , If you create mock cloud-resource file and don't use within your application, That all.(Angular call those files and get those cloud reference and run without any issue)

Try this (I cann't specifically remember where is it).
http://docs.appgyver.com/supersonic/tutorial/third-mile/

**Comment by jublo** [comment]
@GayanJayasundara Thanks, that solved the issue for now.

**Comment by GayanJayasundara** [comment]
@jublo No Problem.

**Comment by jasongilmour** [comment]
@GayanJayasundara I can't initialise data for my app, I just keep getting [this output in terminal](https://github.com/AppGyver/steroids/files/259604/debugging-message.txt)
