### ISSUE TITLE
Adndroid Emulator or Push fails

### ISSUE THREAD

**Issue by kiwina** [AppGyver/steroids#955]
Error: Cannot find module 'E:\ANDROID\sdk\platform-tools\adb'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
Shouldn't even add the full path as they are set as system variables

**Comment by satusuuronen** [comment]
What is the command you are running?
The default Android emulator is not guaranteed to work on Windows. Have you tried [Genymotion](http://docs.appgyver.com/tooling/cli/emulators/genymotion/) instead?

**Comment by stuartandrews93** [comment]
I've just started using Steroids and Supersonic, but when I try run the app in Genymotion is loads for about 5-10 minutes then announces that it couldn't find "steroids" (I did name the device that by the way). Any ideas?
